import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Providers} from "./providers";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nexus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <SessionProvider> */}
          <Providers>
              {children}
          </Providers>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
