import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Providers} from "./providers";
import { SessionProvider } from "next-auth/react";
import Link from "next/link";
import Navbar from "@/app/ui/navbar"
import "./globals.css";
import { getServerSession } from "next-auth";
import Logout from "@/app/ui/logout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nexus",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen bg-gradient-to-tr from-white to-gray-300">
          {/* <SessionProvider> */}
        
          <Navbar/>
        
          {children}
        {/* </SessionProvider> */}
        </main>
      </body>
    </html>
  );
}